### ISSUE TITLE
Couldn't access the project.

### ISSUE THREAD

**Issue by Madhan-coder** [manojpawarsj12/apptracker#2]
Here is the CMD info.

"(venv) C:\Users\Public\Time Engine>apptracker -start
commands:
apptracker -show show
apptracker -start start
apptracker -clean clean
commands:
apptracker -show show
apptracker -start start
apptracker -clean clean
usage: apptracker [-h] [-start START] [-show SHOW] [-clean CLEAN]
apptracker: error: argument -start: expected one argument"

app did not start when entered apptracker -start

**Comment by manojpawarsj12** [comment]
@Madhan-coder 
apptracker -start start
